# Generated by Django 4.1.7 on 2023-03-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_project_created_project_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Tittle',
            new_name='tittle',
        ),
    ]
